version: '3.7'
services:
   main:
      image: cs511p1-main
      hostname: main
      tty: true
      stdin_open: true
      ports:
        - 8080:8080
        - 8081:8081
      command: ["/bin/bash", "start-main.sh"]
      networks:
         - localnet
   worker1:
      image: cs511p1-worker
      hostname: worker1
      tty: true
      stdin_open: true
      command: ["/bin/bash", "start-worker.sh"]
      networks:
         - localnet
   worker2:
      image: cs511p1-worker
      hostname: worker2
      tty: true
      stdin_open: true
      command: ["/bin/bash", "start-worker.sh"]
      networks:
         - localnet
   worker3:
      image: cs511p1-worker
      hostname: worker3
      tty: true
      stdin_open: true
      command: ["/bin/bash", "start-worker.sh"]
      networks:
         - localnet
   arangodb:
      image: arangodb
      ports:
         - 8529:8529
      volumes:
         - ./data :/data/db
      command: ["arangod", "--server.storage-engine=rocksdb"]
      networks:
         - localnet

volumes:
  data:

# networks:
#    localnet:
#       attachable: true

networks:
   localnet:
      driver: bridge