version: '3.7'
services:
   main:
      image: cs511p1-main
      hostname: main
      tty: true
      stdin_open: true
      ports:
        - 8080:8080
        - 8081:8081
      command: ["/bin/bash", "start-main.sh"]
      networks:
         - localnet
   worker1:
      image: cs511p1-worker
      hostname: worker1
      tty: true
      stdin_open: true
      command: ["/bin/bash", "start-worker.sh"]
      networks:
         - localnet
   worker2:
      image: cs511p1-worker
      hostname: worker2
      tty: true
      stdin_open: true
      command: ["/bin/bash", "start-worker.sh"]
      networks:
         - localnet
   mongodb:
      image: mongo:latest
      # environment:
      #    MONGO_INITDB_ROOT_USERNAME: root
      #    MONGO_INITDB_ROOT_PASSWORD: rootpassword
      ports:
         - 27017:27017
      volumes:
         - mongodb_data_container:/data/db
      networks:
         - localnet

volumes:
  mongodb_data_container:

networks:
   localnet:
      attachable: true